---
- name: Create Systemd path and service units
  hosts: web
  gather_facts: true
  become: true
  vars:
   path_name: 
   service_name: 
   callback: 
   hostconfigkey: 
   watched_file: 
   path_des: 
   service_des: 

  tasks:
   
  - name: setup path
    template:
     src: path.j2
     dest: /etc/systemd/system/{{ path_name }}.path
     owner: root
     group: root
     mode: 644

 
  - name: setup service
    template:
     src: service.j2
     dest: /etc/systemd/system/{{ service_name }}.service
     owner: root
     group: root
     mode: 644

  - name: activate systemd units
    service:
      name: "{{ path_name }}.path"
      state: started
      enabled: yes

 
