---
- name: Rescue a possible comprimised  Account system
  hosts: rhel
  gather_facts: true
  become: true

  vars:
   my_repo: system_resources.git
   my_repo_host: github.com
   my_repo_user: nmartins0611
   my_repo_url: git@{{ my_repo_host }}:{{ my_repo_user }}/{{ my_repo }}
   my_repo_key: /Users/nmart/.ssh/id_rsa
   id_initial: 0
   myuser: 
   mypass: 
   todays_date: 0

  tasks:

   - name: Ansible fact - ansible_date_time
     set_fact:
      todays_date: "{{ ansible_date_time.date }}"

   - name: Getting Job history for host
     uri:
       url: https://controller.nostromo.co.za/api/v2/hosts/3/job_host_summaries/?job__job_template_id=20&created__regex={{ todays_date }}
       user: "{{ myuser }}"
       password: "{{ mypass }}"
       force_basic_auth: true
       method: "GET"
       status_code: "200"
       validate_certs: no
     register: "job_details"  
       
   - name: Counting incidents
     set_fact:
       counter: "{{ job_details | regex_findall('processed') | length }}"
    
   - name: Retrieve user files
     git:
      repo: https://github.com/nmartins0611/system_resources
      dest: /restore
      clone: yes
 
   - name: Restore desired user database files
     copy: 
      src:  /restore/passwd
      dest: /etc/
      owner: root
      group: root
      mode: 0644
      remote_src: yes

   - name: Cleanup 
     file:
       path: /restore
       state: absent

   - name: Isolate node - too many compliance issues - Logging support ticket
     debug:
       msg: "Oh No! Lock Down ansible_nodename"
     when: counter > 5
