---
- name: Rescue a possible comprimised  Account system
  hosts: rhel
  gather_facts: true
  become: true
  collections:
    - servicenow.itsm

  vars:
   my_repo: 
   my_repo_host: 
   my_repo_user: 
   my_repo_url: git@{{ my_repo_host }}:{{ my_repo_user }}/{{ my_repo }}
   my_repo_key: 
   todays_date: 0

  tasks:

   - name: check job count for today
     include_role:
      name: ../roles/job_counter
    
   - name: remediate comprimised accounts
     include_role:
      name: ../roles/rescue_accounts
